# RGB_MATRIX_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes

COMBO_ENABLE = yes
KEY_LOCK_ENABLE = yes
TAP_DANCE_ENABLE = yes

UNICODE_COMMON = yes
UNICODE_ENABLE = yes

TRIA_LANG_USE_ENRU = yes

SRC += tria.c